### ISSUE TITLE
Cannot accept first screenshot as baseline - no accept or decline buttons are shown

### ISSUE THREAD

**Issue by pashidlos** [visual-knight/platform-community-edition#12]
Core library keep throwing error 
```
TypeError: Cannot read property 'misMatchTolerance' of null

      at VisualKnightCore.<anonymous> (node_modules/@visual-knight/core/src/process-screenshot.ts:49:61)
      at fulfilled (node_modules/@visual-knight/core/lib/process-screenshot.js:4:58)
```

![1](https://user-images.githubusercontent.com/5182956/77175544-16afac00-6ac3-11ea-9294-5069b7ff73cc.png)

Expected result:
- Error in console has link to test session where baseline needs to be accepted
- Accept and decline buttons are present
- Status is UNRESOLVED

**Workaround for now**
Set `autoBaseline: true` - current image is taken as baseline

**Comment by pashidlos** [comment]
I prepared fix but it's dependent on https://github.com/visual-knight/platform-community-edition/pull/10

Can create PR after it's merged

**Comment by pashidlos** [comment]
@MitkoTschimev here is the fix 
https://github.com/visual-knight/platform-community-edition/pull/19
