### ISSUE TITLE
Cannot start api service 

### ISSUE THREAD

**Issue by pashidlos** [visual-knight/platform-community-edition#25]
node `v12.14.1`
npm `6.13.4`

Steps:
1. clone repo
2. `npm i`
3. `npx ng serve api`

```
PS C:\work\platform-community-edition> npx ng serve api
Starting type checking service...
Using 6 workers with 2048MB memory limit
Type checking in progress...
Hash: 5875a0559989f54eca86
Built at: 04/07/2020 3:00:58 PM
Entrypoint main = main.js main.js.map
chunk {main} main.js, main.js.map (main) 107 KiB [entry] [rendered]
Debugger listening on ws://localhost:7777/7d635fbc-96ab-456f-af52-46b5df70172c
Debugger listening on ws://localhost:7777/7d635fbc-96ab-456f-af52-46b5df70172c
For help, see: https://nodejs.org/en/docs/inspector
[Nest] 20888   - 04/07/2020, 3:01 PM   [NestFactory] Starting Nest application...
[Nest] 20888   - 04/07/2020, 3:01 PM   [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (SharedModule). Please verify whether each exported unit is available in this particular context. +52ms
Error: Nest cannot export a provider/module that is not a part of the currently processed module (SharedModule). Please verify whether each exported unit is available in this particular context.
    at Module.validateExportedProvider (C:\work\platform-community-edition\node_modules\@nestjs\core\injector\module.js:251:19)
    at Module.addCustomExportedProvider (C:\work\platform-community-edition\node_modules\@nestjs\core\injector\module.js:235:43)
    at Module.addExportedProvider (C:\work\platform-community-edition\node_modules\@nestjs\core\injector\module.js:221:25)
    at NestContainer.addExportedProvider (C:\work\platform-community-edition\node_modules\@nestjs\core\injector\container.js:112:16)
    at DependenciesScanner.insertExportedProvider (C:\work\platform-community-edition\node_modules\@nestjs\core\scanner.js:177:24)
    at C:\work\platform-community-edition\node_modules\@nestjs\core\scanner.js:104:50
    at Array.forEach (<anonymous>)
    at DependenciesScanner.reflectExports (C:\work\platform-community-edition\node_modules\@nestjs\core\scanner.js:104:17)
    at DependenciesScanner.scanModulesForDependencies (C:\work\platform-community-edition\node_modules\@nestjs\core\scanner.js:57:18)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by pashidlos** [comment]
Finally I found the issue - `VK_DATABASE` env variable was not set 
As it was removed from root `.envtemplate` https://github.com/visual-knight/platform-community-edition/commit/833b53a0f18c74e59aa4d5305f9e73b8be4d2bcc
Fix and validation is added in https://github.com/visual-knight/platform-community-edition/pull/30
