### ISSUE TITLE
API. PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by pashidlos** [visual-knight/platform-community-edition#28]
When I send image around 100 KB 
Example image
![large](https://user-images.githubusercontent.com/5182956/78943944-1e101700-7abd-11ea-8df3-6867f7daa2ab.png)

Error
```
api_1        | [Nest] 19   - 04/09/2020, 9:40 PM   [ExceptionsHandler] request entity too large +47937ms
api_1        | PayloadTooLargeError: request entity too large
api_1        |     at readStream (/api/node_modules/raw-body/index.js:155:17)
api_1        |     at getRawBody (/api/node_modules/raw-body/index.js:108:12)
api_1        |     at read (/api/node_modules/body-parser/lib/read.js:77:3)
api_1        |     at jsonParser (/api/node_modules/body-parser/lib/types/json.js:135:5)
api_1        |     at Layer.handle [as handle_request] (/api/node_modules/express/lib/router/layer.js:95:5)
api_1        |     at trim_prefix (/api/node_modules/express/lib/router/index.js:317:13)
api_1        |     at /api/node_modules/express/lib/router/index.js:284:7
api_1        |     at Function.process_params (/api/node_modules/express/lib/router/index.js:335:12)
api_1        |     at next (/api/node_modules/express/lib/router/index.js:275:10)
api_1        |     at expressInit (/api/node_modules/express/lib/middleware/init.js:40:5)
```

Temp workaround 
https://stackoverflow.com/questions/52783959/nest-js-request-entity-too-large-payloadtoolargeerror-request-entity-too-larg

I guess it should be implemented as configuration setting

**Comment by pashidlos** [comment]
New configuration variable is added https://github.com/visual-knight/platform-community-edition/pull/31
